### ISSUE TITLE
unit tests failing in nightly 

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/update-testing#45] opened 2023-01-31 03:47 UTC
Build link: https://drone.owncloud.com/owncloud/update-testing/1883/1/6
 Most of the unit tests are failing from `matrix-1` to `matrix-9` and needs investigation 

the failure is 
```
Tests\Core\Controller\AvatarControllerTest::testGetAvatarNoAvatar
in_array() expects parameter 2 to be array, null given
```
```
\Files\Tests\Command\TransferOwnershipTest::testTransferUserFolderToExistingUserError
in_array() expects parameter 2 to be array, null given
```

Seems like something changed in `AvatarController`

**Comment by phil-davis** [comment] 2023-02-01 05:56
The full test fail output is:
```
1)Tests\Core\Controller\AvatarControllerTest::testGetAvatarNoAvatar
in_array() expects parameter 2 to be array, null given
/drone/src/owncloud/lib/private/User/SyncService.php:426
/drone/src/owncloud/lib/private/User/SyncService.php:153
/drone/src/owncloud/lib/private/User/SyncService.php:354
/drone/src/owncloud/lib/private/User/SyncService.php:394
/drone/src/owncloud/lib/private/User/Manager.php:423
/drone/src/owncloud/lib/public/Events/EventEmitterTrait.php:50
/drone/src/owncloud/lib/private/User/Manager.php:430
/drone/src/owncloud/lib/private/User/Manager.php:404
/drone/src/owncloud/lib/public/Events/EventEmitterTrait.php:50
/drone/src/owncloud/lib/private/User/Manager.php:410
/drone/src/owncloud/tests/lib/Traits/UserTrait.php:35
/drone/src/owncloud/tests/Core/Controller/AvatarControllerTest.php:79
```

**Comment by saw-jan** [comment] 2023-02-01 09:21
These failures of the ReportTest  tests might be the cause of other test errors:
```bash
1) Tests\Core\Command\User\ReportTest::testCommandInput with data set #0 (true)
Failed asserting that 'We detected that the instance is running on a S3 primary object storage, user directories count might not be accurate\n
+------------------------------------------------+---+\n
| User Report                                    |   |\n
+------------------------------------------------+---+\n
| No backend enabled that supports user counting |   |\n
|                                                |   |\n
| user directories                               | 0 |\n
+------------------------------------------------+---+\n
' contains "+------------------+---+
| User Report      |   |
+------------------+---+
| OC\User\Database | 1 |
|                  |   |
| guest users      | 0 |
|                  |   |
| total users      | 1 |
|                  |   |
| user directories | 1 |
+------------------+---+
".
/drone/src/owncloud/tests/Core/Command/User/ReportTest.php:130

2) Tests\Core\Command\User\ReportTest::testCommandInput with data set #1 (false)
Failed asserting that 'We detected that the instance is running on a S3 primary object storage, user directories count might not be accurate\n
+------------------------------------------------+---+\n
| User Report                                    |   |\n
+------------------------------------------------+---+\n
| No backend enabled that supports user counting |   |\n
|                                                |   |\n
| user directories                               | 0 |\n
+------------------------------------------------+---+\n
' contains "+------------------+---+
| User Report      |   |
+------------------+---+
| OC\User\Database | 1 |
|                  |   |
| guest users      | 0 |
|                  |   |
| total users      | 1 |
|                  |   |
| user directories | 1 |
+------------------+---+
".
/drone/src/owncloud/tests/Core/Command/User/ReportTest.php:130
```

I fake passed the ReportTests and all other tests were passing (https://drone.owncloud.com/owncloud/update-testing/1914/1/6)

**Comment by saw-jan** [comment] 2023-02-01 09:39
Something happened after these functions got executed
https://github.com/owncloud/core/blob/be219e66c43c04bd3ada51b14a6248ca79c1fd49/tests/Core/Command/User/ReportTest.php#L139-L156
```php

	private function overwriteConfigWithObjectStorage() {
		$config = $this->createMock('\OCP\IConfig');
		$config->expects($this->any())
			->method('getSystemValue')
			->willReturn(['objectstore' => true]);

		$this->overwriteService('AllConfig', $config);
	}

	private function overwriteAppManagerWithObjectStorage() {
		$config = $this->createMock('\OCP\App\IAppManager');
		$config->expects($this->any())
			->method('isEnabledForUser')
			->willReturn(true);

		$this->overwriteService('AppManager', $config);
	}
```
in the test https://github.com/owncloud/core/blob/be219e66c43c04bd3ada51b14a6248ca79c1fd49/tests/Core/Command/User/ReportTest.php#L80-L90
```php

	/**
	 * @param bool $objectStorageUsed
	 * @dataProvider objectStorageProvider
	 * @return void
	 */
	public function testCommandInput($objectStorageUsed) {
		if ($objectStorageUsed) {
			$this->overwriteConfigWithObjectStorage();
			$this->overwriteAppManagerWithObjectStorage();
		}

```

**Comment by phil-davis** [comment] 2023-02-01 12:19
The problem in AvatarControllerTest is with `$this->createUser('userid', 'pass');`
Eventually it is in SyncService `readUserConfig($uid, $app, $key)` which calls `getUserKeys` and that looks like it returns null.

I guess that it will be something to do with the creation_time that has been added to `oc_accounts` table. And maybe somehow in the update from an old ownCloud version it has not run the migration properly to add the new column to the table? (Just a guess)

@DeepDiver1975 @jvillafanez are you (or someone) able to have a look at what is happening with these tests? They are being run after CI does an upgrade from an older oC10 version to the current code.

**Comment by jvillafanez** [comment] 2023-02-01 12:58
> Something happened after these functions got executed
https://github.com/owncloud/core/blob/be219e66c43c04bd3ada51b14a6248ca79c1fd49/tests/Core/Command/User/ReportTest.php#L139-L156

I think the services that were overwritten weren't restored after the test. This means that the rest of the tests depending on those services were run with those mocks, not the real services as they expect.

What happens is:
1. Report test overwrites the services with the mocks
2. Report test fails
3. Report test doesn't restore the overwritten service due to the assert failure.
4. Avatar controller tests (expecting a real service) fails due to mock service being misconfigured.

In general, if the test class needs to overwrite services, it should be placed in the `setUp` method, and restoring the service should be placed in the `tearDown` method. If it's only one test requiring the service overwrite, you can do it in the test itself, but the restoring should still be placed in the `tearDown` method in order to ensure it's reverted even if the test fails (which isn't the case)

**Comment by saw-jan** [comment] 2023-02-02 04:15
Restoring Service in the teardown of the ReportTest made other tests pass.

Without restoring the service:
```bash
ERRORS!
Tests: 10717, Assertions: 49546, Errors: 853, Failures: 14, Skipped: 136.
```

With Service restore:
```bash
FAILURES!
Tests: 10717, Assertions: 59564, Failures: 2, Skipped: 90.
```

But ReportTest tests still have failures:
```bash
There were 2 failures:

1) Tests\Core\Command\User\ReportTest::testCommandInput with data set #0 (true)

Failed asserting that 'We detected that the instance is running on a S3 primary object storage, user directories count might not be accurate\n
+------------------------------------------------+---+\n
| User Report                                    |   |\n
+------------------------------------------------+---+\n
| No backend enabled that supports user counting |   |\n
|                                                |   |\n
| user directories                               | 0 |\n
+------------------------------------------------+---+\n
' contains "+------------------+---+
| User Report      |   |
+------------------+---+
| OC\User\Database | 1 |
|                  |   |
| guest users      | 0 |
|                  |   |
| total users      | 1 |
|                  |   |
| user directories | 1 |
+------------------+---+
".
/drone/src/owncloud/tests/Core/Command/User/ReportTest.php:132

2) Tests\Core\Command\User\ReportTest::testCommandInput with data set #1 (false)

Failed asserting that '+------------------------------------------------+---+\n
| User Report                                    |   |\n
+------------------------------------------------+---+\n
| No backend enabled that supports user counting |   |\n
|                                                |   |\n
| user directories                               | 0 |\n
+------------------------------------------------+---+\n
' contains "+------------------+---+
| User Report      |   |
+------------------+---+
| OC\User\Database | 1 |
|                  |   |
| guest users      | 0 |
|                  |   |
| total users      | 1 |
|                  |   |
| user directories | 1 |
+------------------+---+
".
/drone/src/owncloud/tests/Core/Command/User/ReportTest.php:132
```

**Comment by saw-jan** [comment] 2023-02-02 07:25
After upgrading from `v8` or `v9` to `v10.12`, the `oc_accounts` table is empty. See [output](https://drone.owncloud.com/owncloud/update-testing/1925/1/6)
But when upgrading from older `v10` to `v10.12`, `oc_accounts` table has some records. See [output](https://drone.owncloud.com/owncloud/update-testing/1925/2/6)

**Comment by grgprarup** [comment] 2023-02-13 06:05
Moved to backlog until some response and decisions are made.

**Comment by SwikritiT** [comment] 2023-04-17 07:15
Just a reminder that the unit tests are still failing, it's been a month. Can we do something about this issue?

cc: @saw-jan @jvillafanez @phil-davis @DeepDiver1975

**Comment by jvillafanez** [comment] 2023-04-17 10:43
Did the fix discussed in https://github.com/owncloud/update-testing/issues/45#issuecomment-1413129426 got merged? I don't see the change in the master branch. That should reduce the number of failures considerably.

From there, I'm not sure where the problem could be. We might need some fresh runs. The 2 remaining failures could be cause by some remnant data from a previous run, so we need to discard this possibility.

**Comment by phil-davis** [comment] 2023-04-17 10:49
"Restoring Service in the teardown of the ReportTest made other tests pass."

@saw-jan do you have a branch/code somewhere that does this?

If so, please make a PR for it. Then we think about force-merging that to reduce the number of failures. And then work out what to do about the few remaining fails.

**Comment by saw-jan** [comment] 2023-04-17 11:26
> If so, please make a PR for it. Then we think about force-merging that to reduce the number of failures. And then work out what to do about the few remaining fails.

Okey.
I will have a look if I had made the PR.

**Comment by phil-davis** [comment] 2023-04-18 05:12
https://github.com/owncloud/core/pull/40744 has been merged.
Tonight we will get another CI run with the latest core, so let's wait and see the results. Then we can sort out the remaining test fails.

**Comment by saw-jan** [comment] 2023-04-19 05:53
```bash
There were 2 failures:

1) Tests\Core\Command\User\ReportTest::testCommandInput with data set #0 (true)
Failed asserting that 'We detected that the instance is running on a S3 primary object storage, user directories count might not be accurate\n
+------------------------------------------------+---+\n
| User Report                                    |   |\n
+------------------------------------------------+---+\n
| No backend enabled that supports user counting |   |\n
|                                                |   |\n
| user directories                               | 0 |\n
+------------------------------------------------+---+\n
' contains "+------------------+---+
| User Report      |   |
+------------------+---+
| OC\User\Database | 1 |
|                  |   |
| guest users      | 0 |
|                  |   |
| total users      | 1 |
|                  |   |
| user directories | 1 |
+------------------+---+
".

/drone/src/owncloud/tests/Core/Command/User/ReportTest.php:136

2) Tests\Core\Command\User\ReportTest::testCommandInput with data set #1 (false)
Failed asserting that '+------------------------------------------------+---+\n
| User Report                                    |   |\n
+------------------------------------------------+---+\n
| No backend enabled that supports user counting |   |\n
|                                                |   |\n
| user directories                               | 0 |\n
+------------------------------------------------+---+\n
' contains "+------------------+---+
| User Report      |   |
+------------------+---+
| OC\User\Database | 1 |
|                  |   |
| guest users      | 0 |
|                  |   |
| total users      | 1 |
|                  |   |
| user directories | 1 |
+------------------+---+
".

/drone/src/owncloud/tests/Core/Command/User/ReportTest.php:136
```

Now these two failures remain. And the issue is commented here:

> After upgrading from `v8` or `v9` to `v10.12`, the `oc_accounts` table is empty. See [output](https://drone.owncloud.com/owncloud/update-testing/1925/1/6)
> 
> ```shell
> + mysql -u owncloud -p"owncloud" -h mysql -P 3306 -D owncloud -e "use owncloud;select * from oc_users;"
> uid	displayname	password
> admin	NULL	1|$2y$10$ka1ANDgXBneVtcp8YkUAPOvygZhdlgKE5QYmlwHZNOZb3X2UZFI1u
> 
> + mysql -u owncloud -p"owncloud" -h mysql -P 3306 -D owncloud -e "use owncloud;select * from oc_accounts;"
> 
> + mysql -u owncloud -p"owncloud" -h mysql -P 3306 -D owncloud -e "use owncloud;SELECT backend, count(*) as count FROM oc_accounts GROUP BY backend;"
> ```
> 
> But when upgrading from older `v10` to `v10.12`, `oc_accounts` table has some records. See [output](https://drone.owncloud.com/owncloud/update-testing/1925/2/6)
> 
> ```shell
> + mysql -u owncloud -p"owncloud" -h mysql -P 3306 -D owncloud -e "use owncloud;select * from oc_users;"
> uid	displayname	password
> admin	NULL	1|$2y$10$AOJbElviPeOB727K3kwFiOMglVEFQVVY0Rr0VryJD66OU2kY9JJlW
> 
> + mysql -u owncloud -p"owncloud" -h mysql -P 3306 -D owncloud -e "use owncloud;select * from oc_accounts;"
> id	email	user_id	lower_user_id	display_name	quota	last_login	backend	home	state	creation_time
> 1	NULL	admin	admin	admin	NULL	0	OC\\User\\Database	/drone/src/data/admin	1	0
> 
> + mysql -u owncloud -p"owncloud" -h mysql -P 3306 -D owncloud -e "use owncloud;SELECT backend, count(*) as count FROM oc_accounts GROUP BY backend;"
> backend	count
> OC\\User\\Database	1
> ```

**Comment by jvillafanez** [comment] 2023-04-19 08:43
I assume that version 10 trigger a login at some point during the installation, and the admin was inserted in the accounts table due to that login. However, that login doesn't happen in version 8 and 9.
If this is the case, I think the easiest solution is to trigger a login.

For the test itself, I'm not sure if assuming the admin user will be present in the tests is a good idea.
The other option is to replace the tests with proper unit tests. The dependencies for the report command aren't mocked, and that's what causing the issue since the state of the installation isn't the one expected.

**Comment by jvillafanez** [comment] 2023-04-19 10:15
https://github.com/owncloud/core/pull/40748 changes the tests to mock as many dependencies as possible. That should fix the tests.

In any case, I'm not sure how valuable the unit tests can be for the upgrade test because, by definition, the unit tests should have their dependencies mocked. I know there are non-unit tests there, but I don't think we should rely on those. It makes more sense to run acceptance tests which are expected to run through the whole stack.

**Comment by phil-davis** [comment] 2023-04-19 10:21
This will get the CI green again, so we can get that merged today and (hopefully) get green CI tonight. We can then think about what tests are actually good to run after an upgrade.

**Comment by saw-jan** [comment] 2023-04-20 05:05
CI is green. I am closing this here

**Closed by saw-jan** 2023-04-20 05:05 UTC
Labels: QA-Team
